# CODER HOUSE - ENTREGA 1
### Coderhouse - Data Science - Comisi칩n 61615
Alumna Daniela Gonz치lez

In [ ]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [ ]:
path = "/content/age_std_suicide_rates_1990-2022.csv.csv"
df=pd.read_csv(path)
df.head()
#Se muestran las primeras filas de la tabla. Podemos ver que muchas de estas tienen problemas,
#por lo que hyay que limpiar la informaci칩n antes de poder continuar con las gr치ficas

,RegionCode,RegionName,CountryCode,CountryName,Year,Sex,SuicideCount,CauseSpecificDeathPercentage,StdDeathRate,DeathRatePer100K,Population,GDP,GDPPerCapita,GNI,GNIPerCapita,InflationRate,EmploymentPopulationRatio
0,EU,Europe,ALB,Albania,1992.0,Male,33.0,0.331959,2.335802,2.076386,3247039.0,6.521750e+08,200.852220,9.061842e+08,1740.0,226.005421,45.315
1,EU,Europe,ALB,Albania,1992.0,Female,14.0,0.191860,0.866420,0.874563,3247039.0,6.521750e+08,200.852220,9.061842e+08,1740.0,226.005421,45.315
2,EU,Europe,ALB,Albania,1993.0,Male,46.0,0.477724,3.330938,2.937233,3227287.0,1.185315e+09,367.279225,1.024263e+09,2110.0,85.004751,47.798
3,EU,Europe,ALB,Albania,1993.0,Female,27.0,0.385164,1.755077,1.686025,3227287.0,1.185315e+09,367.279225,1.024263e+09,2110.0,85.004751,47.798
4,EU,Europe,ALB,Albania,1994.0,Male,37.0,0.419406,2.678796,2.332619,3207536.0,1.880951e+09,586.416135,1.216681e+09,2300.0,22.565053,50.086

# Limpieza

In [ ]:
print(df.isnull().sum())
#Se muestran los campos nulos en cada columna

RegionCode                        0
RegionName                       56
CountryCode                      56
CountryName                      56
Year                             56
Sex                              56
SuicideCount                     56
CauseSpecificDeathPercentage     57
StdDeathRate                    264
DeathRatePer100K                264
Population                      350
GDP                             416
GDPPerCapita                    416
GNI                             552
GNIPerCapita                    592
InflationRate                   777
EmploymentPopulationRatio       610
dtype: int64

In [ ]:
# df = DataFrame
df_limpio = df.dropna()

In [ ]:
df_limpio = df.dropna(how='all')
#Eliminar filas donde sea nulo

In [ ]:
# Verificar si queda alg칰n valor nulo en el DataFrame limpio
print(df_limpio.isna().any().any())

True

# Gr치ficos